### ISSUE TITLE
Cropped Out Captcha display - Possible to Style HCaptcha? Is it incompatibility in native mobile screen?

### ISSUE THREAD

**Issue by hyfydistro** [hCaptcha/react-hcaptcha#113]
I'm using react-hcaptcha with the Ionic Framework, so I would like to see for cross platforms (native and web). I'm checking with Chrome developer tool and checking via responsive screen size. It looks fine of the web (resizing the client too), but when I choose a device (iPhone XR) it gets cut. Note, I refresh the page after I select the device in order to get that device emulator setup. This is all testing on the Chrome browser.
![h-00](https://user-images.githubusercontent.com/24542308/150648081-0e09be78-bc5a-45c6-a57e-49cdca0b94cf.png)

it's a similar result when I add prop `size="compact"`. It is slightly cropped too.

I'm not sure if this is a bug or incompatibility issue. It has to do with the `iframe` sizing too. Is there a way to style it and persist? Or is there another option or library that I should be using instead?

**Comment by hyfydistro** [comment]
I should add the following dependencies I'm using:
```
"@hcaptcha/react-hcaptcha": "^1.0.0",
"@ionic/core": "^5.8.0",
"@ionic/react": "^5.5.0",
 "react": "^17.0.1",
```

**Comment by brdlyptrs** [comment]
Hi @hyfydistro the checkbox is set to a specific size for both the default and compact size. This is most likely an issue with the element rendering the hCaptcha component having an overflow hidden set on it.

**Comment by hyfydistro** [comment]
Thank you. It is not a problem anymore.
