### ISSUE TITLE
React 18 StrictMode issue

### ISSUE THREAD

**Issue by sadriddin** [hCaptcha/react-hcaptcha#128]
There is an issue with React 18 in StrictMode.  "Only one captcha is permitted per parent container. " error appears in console 
Here is [sandbox](https://codesandbox.io/s/reverent-agnesi-cvmjkf)

**Comment by TelegramUsername** [comment]
Hi team, can i get the expected date for closure of this issue, i am getting affected by this

**Comment by zoryana94** [comment]
Hi,

Sorry for the delay. The issue should be fixed in [our latest 1.3.1 release.](https://github.com/hCaptcha/react-hcaptcha/releases/tag/1.3.1)
Please check it from your side and let us know if everything is working as expected.

Best Regards,
IM Dev Team
