### ISSUE TITLE
Test keys suddenly stopped working on localhost

### ISSUE THREAD

**Issue by tmeumann** [hCaptcha/react-hcaptcha#137]
The test keys [here](https://docs.hcaptcha.com/#test-key-set-publisher-account) suddenly stopped working on localhost today across all my projects.

Please see the attached screenshots. The error text at the top of the component is new, and now if I click the checkbox the component gets stuck loading.

Has there been a regression?

<img width="314" alt="Screen Shot 2022-06-07 at 6 58 13 pm" src="https://user-images.githubusercontent.com/4954220/172341154-c5fa9b2c-0554-4be7-a492-47f1a07ccd5b.png">

<img width="314" alt="Screen Shot 2022-06-07 at 7 03 09 pm" src="https://user-images.githubusercontent.com/4954220/172341263-af5fafeb-b6ff-4602-ab3b-f4cb1a1acd99.png">

**Comment by cpouldev** [comment]
+1 I'm facing the exact same issue too

**Comment by brdlyptrs** [comment]
Test keys should be working locally again, thank you for your patience!

**Comment by tmeumann** [comment]
Can confirm it's working again. Thanks for the speedy fix!
