### ISSUE TITLE
invalid-captcha-id

### ISSUE THREAD

**Issue by vaggos-thanos** [hCaptcha/react-hcaptcha#147]
When is the time to show hCaptcha it throws an error in the console 
error code : cause: "invalid-captcha-id"  message: "Invalid hCaptcha id: 0tb9cvxm5e9m" 

Also, I have checked and the site key is correct can someone help? 

I have React js for the frontend
![Screenshot_1](https://user-images.githubusercontent.com/56397268/178974916-4178748c-2f01-45b0-8a22-16414ee01430.png)

**Comment by brdlyptrs** [comment]
Hi @vaggos-thanos can you provide a way to reproduce this issue? 

This error is thrown when attempting to call a captcha that not longer exists. This usually occurs when the component is re-rendered and the parent component attempts to call the new hCaptcha component with an older ID.

**Comment by vaggos-thanos** [comment]
no when literally the site loads there is no re-render no there is a new error code in the id
![Screenshot_2](https://user-images.githubusercontent.com/56397268/179091586-d3b38274-2eed-47fd-93e3-7be6f2503692.png)

**Comment by vaggos-thanos** [comment]
Yea I fixed it it was a re-render sorry for the trouble

**Comment by brdlyptrs** [comment]
All good, glad you were able to figure it out! @vaggos-thanos
