### ISSUE TITLE
Overlapping description text on mobile view

### ISSUE THREAD

**Issue by hb0** [hCaptcha/react-hcaptcha#148]
Version: `@hcaptcha/react-hcaptcha": "^1.1.0"`.
Client Language: German

The description text is overlapping on a mobile device (iPhone XR, probably Safari Browser):

![IMG_4833](https://user-images.githubusercontent.com/6112241/179967324-0a9244de-e425-4848-9af4-1797e06b16f2.PNG)

**Comment by e271828-** [comment]
@hb0 thanks for the report, it looks like the automatic reflow did not happen in this instance. Not directly related to the react module, but we are reviewing and will adjust as needed.
