### ISSUE TITLE
NextJS Fast-Refresh Bug

### ISSUE THREAD

**Issue by zhiyan114** [hCaptcha/react-hcaptcha#163]
Hey, for some reason, it seems like NextJS's fast-refresh breaks HCaptcha.
Everytime I make code changes, the error pops up.
![image](https://user-images.githubusercontent.com/20156291/207442582-6f937091-c5be-4e57-80e3-a0cc84af7d8b.png)

Is there a workaround for this without disabling nextjs's fast-refresh?

**Comment by zhiyan114** [comment]
Seems like the issue have gone away.

**Comment by wontem** [comment]
@zhiyan114 a new version of `api.js` is released. Please check if it helped. No need to update the `react-hcaptcha`, just try to reproduce the issue

**Comment by zhiyan114** [comment]
Great, it seems like the issue is resolved, I'll reopen it if it happens again..
