### ISSUE TITLE
Secret Key not needed?

### ISSUE THREAD

**Issue by chattago2002** [hCaptcha/react-hcaptcha#167]
Hello everyone.
Sorry for my next question, I'm new to React JS and I'm trying to implement hCaptcha in my project.
I had always used hCaptcha in other environments (php) and the [verification process](https://docs.hcaptcha.com/#verify-the-user-response-server-side) needs a POST request to API with 2 parameters: user-response-token and secret-key.
With react-hcaptcha we can specify (obviously) only the site-key.

My question is: doesn't the secret-key need?
Is this library working without the secret-key, using a different verification process?

**Comment by e271828-** [comment]
@chattago2002 the secret key is what your backend uses to validate the token: https://docs.hcaptcha.com/#verify-the-user-response-server-side

You don't want to use the secret key in your react code. All it does is generate the token that's sent to your backend as usual.
