### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by msutkowski** [hCaptcha/react-hcaptcha#19]
Would you be open to accepting a PR to turn this into a TS project? If not, I'll go ahead and submit the types to `DefinitelyTyped`. 

Thanks!

**Comment by e271828-** [comment]
Hi Matt, we're trying for maximum compatibility, and not everyone is familiar with TS yet. Probably `DefinitelyTyped` is the right approach for now.

**Comment by msutkowski** [comment]
Will do, thanks!

**Comment by msutkowski** [comment]
@e271828- Just a quick note, I've submitted types to DefinitelyTyped. Will note when they're merged in. Thanks.

**Comment by e271828-** [comment]
> @e271828- Just a quick note, I've submitted types to DefinitelyTyped. Will note when they're merged in. Thanks.

Thanks!

**Comment by msutkowski** [comment]
Merged. `yarn add -D @types/hcaptcha__react-hcaptcha` .

**Comment by JacobWennebro** [comment]
I have installed your types and I'm still having this issue in my next.js typescript project, any ideas how to fix this?

[Screenshot](https://i.imgur.com/fySNj4E.jpg)

**Comment by msutkowski** [comment]
> I have installed your types and I'm still having this issue in my next.js typescript project, any ideas how to fix this?
> 
> [Screenshot](https://i.imgur.com/fySNj4E.jpg)

Did you import the component?

**Comment by unlimitedcoder2** [comment]
It is imported with ```ts
import hCaptcha from '@hcaptcha/react-hcaptcha';
```
[Screenshot](https://sharethe.minecraftdoublesmoothstoneslab.website/i/ycfy.png)

**Comment by msutkowski** [comment]
Please try:

```ts
import HCaptcha from '@hcaptcha/react-hcaptcha';
<HCaptcha sitekey="test"/>
```

**Comment by unlimitedcoder2** [comment]
That worked, thanks [Screenshot](https://sharethe.minecraftdoublesmoothstoneslab.website/i/ohsg.png). Is there no way to have it as another name?

**Comment by msutkowski** [comment]
@unlimitedcoder2 You could make a util that imports the class, then exports it as a default, and then you could rename it however you want.

Kinda wonky, but DefinitelyTyped forced me to use `export = HCaptcha` to match how the transpiled module works. 

Example:

```js
// /utils/captcha.ts
import HCaptcha from '@hcaptcha/react-hcaptcha';
export default HCaptcha;
```

Then:
```js
import { default as RenamedCaptcha } from '../utils/captcha';
<form>
  <RenamedCaptcha sitekey="test" />
</form>
```

**Comment by e271828-** [comment]
@msutkowski docs PR gratefully accepted for this. Closed issue is probably not the most discoverable place for the info to live :)

**Comment by msutkowski** [comment]
@e271828- PR opened. Let me know if you need anything else. If that latest version could be released so `resetCaptcha` works, that'd be great :)

**Comment by e271828-** [comment]
@msutkowski Great, thank you. We're planning to ship the new version this week.
