### ISSUE TITLE
Error sitekey on Vercel deployment

### ISSUE THREAD

**Issue by matteomontipo** [hCaptcha/react-hcaptcha#192]
On localhost it works fine using the test sitekey,
while on production (vercel deployment) I get this error frontend:

`hCaptcha has failed to initialize. Please see the developer tools console for more information.`

chrome console:
`Missing sitekey - https://hcaptcha.com/docs/configuration#jsapi`

I've set the env variable through Vercel, and locally via .env.local as I usually do, I don't understand what's wrong.
I double checked the sitekey on hcaptcha and vercel and it matches. Variable on Vercel is set for all (production, preview and development).

the code, which works fine locally is:

```
<HCaptcha
    sitekey={ process.env.HCAPTCHA_SITEKEY }
    onVerify={ setToken }
    onError={ () => setToken(null) }
    onExpire={ () => setToken(null) }
    // theme='dark'
/>
```

**UPDATE:** I think I understood where the issue is, it must be this env which is server only, Nextjs requires NEXT_PUBLIC_ env variables for client side components. So I think I have to make it into a server component, or is there any issues with exposing the sitekey publicly using NEXT_PUBLIC_? I see the keys are domain bound from hCaptcha anyway, does that suffice as a security measure?

**Comment by zoryana94** [comment]
Hi @matteomontipo,

It's great that you have found the solution.
It should be good to use NEXT_PUBLIC_ variable. Alternatively, you can try using [dotenv](https://www.npmjs.com/package/dotenv) or [next.config.js env](https://nextjs.org/docs/app/api-reference/next-config-js/env).
The sitekey does not represent the secret information. The security is achieved using a combination of the sitekey and the secret on the server side.

Best Regards,
IMI Dev Team
