### ISSUE TITLE
invalid-captcha-id for one blog page with different routes

### ISSUE THREAD

**Issue by cybranker** [hCaptcha/react-hcaptcha#196]
Hello. I have a blog page on a site with different translations for an article, under these routes:

/blog/name-blog-en-version/
/ru/blog/name-blog-ru-version/
/ua/blog/name-blog-ua-version/

When switching versions of "ru" and "ua", everything works fine, but when switching "ru" or "ua" to "en", it gives an error "invalid-captcha-id", also when switching from "en" to "ru" or "ua" error! What could be the problem?

![0ee5bcfb35](https://github.com/hCaptcha/react-hcaptcha/assets/59914565/8e7a945e-9725-4ea7-b38b-056457d3e5c7)

**Comment by zoryana94** [comment]
Hi @cybranker ,

[As stated in our docs](https://docs.hcaptcha.com/configuration#error-codes), `invalid-captcha-id` error means that “captcha does not exist for ID provided”. And the action would be to “check to make sure the captcha rendered matches the ID stored. Each hCaptcha client rendered contains a new ID.”

We’d also suggest to [take a look at the similar closed issue](https://github.com/hCaptcha/react-hcaptcha/issues/147).

If it is not helpful, could you please provide us with the way to reproduce the issue?
Please let us know if you have any questions or concerns.

Best Regards,
hCaptcha Dev Team

**Comment by cybranker** [comment]
@zoryana94 A similar closed issue helped, thanks.

**Comment by zoryana94** [comment]
Hi @cybranker ,

Thank you a lot for confirming! And thank you for helping us build better products!
Hope you will enjoy using hCaptcha!

Best Regards,
hCaptcha Dev Team
