### ISSUE TITLE
Triggering issue

### ISSUE THREAD

**Issue by reeexpert** [hCaptcha/react-hcaptcha#197]
Hello there. I've been facing a problem when I click on the button that triggers the invisible hCaptcha in my Next.js project. Sometimes it doesn't trigger at all, I would have to refresh the page sometimes multiple times for it to work. And this happens from time to time and mostly on mobile as well. I'm not sure if that's a problem with hCaptcha or my code.

my _app.jsx
![image](https://github.com/hCaptcha/react-hcaptcha/assets/127796811/0354855b-bb08-4e9b-878d-43b5d275d5a7)

my Search.js component:
![image](https://github.com/hCaptcha/react-hcaptcha/assets/127796811/3661d158-a6d3-4a33-a667-ce99490f059e)
![image](https://github.com/hCaptcha/react-hcaptcha/assets/127796811/c2c3d551-e1bb-4d1c-bc21-44e4fa0e4815)
![image](https://github.com/hCaptcha/react-hcaptcha/assets/127796811/fc7df9c9-a222-42b8-8c8f-20628009a812)

As you can see the button triggers handleSubmit() which does trigger the invisble captcha then if the captcha is solved it send the token and other suff to my api which verifies the token and approve the request. I think the problem might have something to do with loading the hCaptcha script or caching i'm not sure but I hope you could help me with that. Thanks

**Comment by zoryana94** [comment]
Hi @reeexpert ,

I see that you load hCaptcha in your `_app.jsx`
That is not needed, as hCaptcha loads when you place HCaptcha component.
Please check if removing it helps to fix the issue.

Also could you please try adding `{async: true}` as the argument to the `execute`?
You can also get the token the following way:
```
const executeCaptcha = async () => {
    try {
      const captchaResponse = await captchaRef.current.execute({
        async: true
      });
      const responseToken = captchaResponse.response;

      console.log('Verified asynchronously: ', responseToken);
    } catch (error) {
      console.log(error);
    }
  };
```

I checked the react-hCaptcha in the test Next app and I couldn’t reproduce any issues.
So, if mentioned above doesn’t help, it would be good if you send us some basic app that we can start and reproduce the issue.

Best Regards,
hCaptcha Dev Team

**Comment by zoryana94** [comment]
Hi @reeexpert ,

I'm glad the issue is fixed!
Thank for reaching out to us and helping to improve the overall experience with hCaptcha!
Hope you will enjoy using our products!

Best Regards,
hCaptcha Dev Team
