### ISSUE TITLE
The hCaptcha cannot be used when the modal is open.

### ISSUE THREAD

**Issue by antai0926** [hCaptcha/react-hcaptcha#210]
Test: [Codesandbox](https://codesandbox.io/s/radix-modal-hcaptcha-problem-forked-mdvxnk?file=/src/HCaptchaDialog/index.js)
Browser: MacOS / Chrome 119.0.6045.159 (arm64):

Steps:

- Click Open Radix modal button
- Click hcaptcha checkbox
- Select the picture on the iframe

Expected:

- The hcaptcha images can be selected, and the verification button can be pressed.

Actual:

- The hCaptcha iframe is closed, and it is not possible to select images or complete the verification.

**Comment by zoryana94** [comment]
Hi @antai0926,

Thank you a lot for notifying us! And thank you so much for preparing the Codesandbox app!
It was very helpful, I could reproduce the issue. We will discuss it with the team and will keep you posted on any updates.

Best Regards,
hCaptcha Dev Team

**Comment by faris-imi** [comment]
Hi @antai0926,

The issue should be resolved now.
Please check it from your side.

Best Regards,
hCaptcha Dev Team

**Comment by antai0926** [comment]
Thank you. It works fine now.
