### ISSUE TITLE
Hello, I've just created a hCaptcha Go middleware

### ISSUE THREAD

**Issue by kataras** [hCaptcha/react-hcaptcha#22]
Hello contributors, @alikoneko, @brdlyptrs

I know this may not be the right place to ask but I couldn't find other repository to do it.

I've just pushed the <https://github.com/kataras/hcaptcha> repository which is the first hCaptcha web server's middleware for [Go](https://golang) developers. My question is, do you have a place/page that developers can find their hCaptcha clients depending on the programming language they use e.g. at <https://docs.hcaptcha.com/> or somewhere else so I can put this package on?

Thanks,
Gerasimos Maropoulos. Author of the [Iris Web Framework](https://iris-go.com)

**Comment by e271828-** [comment]
Hi Gerasimos, looks good! We will put up a new repo in the hCaptcha org to track this shortly, as there are getting to be too many integrations for us to keep up to date by ourselves.

**Comment by e271828-** [comment]
We're putting this into https://github.com/hCaptcha/hcaptcha-integrations-list now. Thanks!

**Comment by kataras** [comment]
Hello @e271828- , that's great news! I will make sure that kataras/hcaptcha will always be up-to-date.
