### ISSUE TITLE
Hcaptcha shows blank in Europe regions

### ISSUE THREAD

**Issue by carlwatermelon** [hCaptcha/react-hcaptcha#228]
Hi, I am using Hcaptcha in my project, it works fine for most of our users, but European users only see a blank square. I connected to a VPN in Germany and saw the same problem

In Europe:
<img width="360" alt="image" src="https://github.com/hCaptcha/react-hcaptcha/assets/160366944/ac73714b-9e89-4c51-9934-887294d916c2">
<img width="775" alt="image" src="https://github.com/hCaptcha/react-hcaptcha/assets/160366944/2bed3ce7-4302-4e5a-9de9-234346594a65">

And it looks like this:
<img width="311" alt="image" src="https://github.com/hCaptcha/react-hcaptcha/assets/160366944/1ec34e34-f343-40e7-9731-72f21370ecc6">

In other regions:
<img width="362" alt="image" src="https://github.com/hCaptcha/react-hcaptcha/assets/160366944/5b76913d-1293-4e31-83b8-5a079c4ec363">
<img width="549" alt="image" src="https://github.com/hCaptcha/react-hcaptcha/assets/160366944/af649b2f-e943-4cc8-a843-ab4da26f206d">

**Comment by e271828-** [comment]
@carlwatermelon This will be something specific to your site, not hCaptcha. Please open a ticket via support@hcaptcha.com
