### ISSUE TITLE
`execute` typing issue for v1.10.2

### ISSUE THREAD

**Issue by JAD3N** [hCaptcha/react-hcaptcha#235]
The new release made changes to the typings which caused my CI to fail on type-checking. I've submitted a pull request to resolve the issue: https://github.com/hCaptcha/react-hcaptcha/pull/234

**Comment by zoryana94** [comment]
Hi @JAD3N ,

Thank you for notifying us!
Looking into it

**Comment by zoryana94** [comment]
Hi @JAD3N ,
your changes have been released in [1.10.3](https://github.com/hCaptcha/react-hcaptcha/releases/tag/1.10.3)

could you please confirm the issue is fixed?

**Comment by JAD3N** [comment]
I just upgraded the version of hCaptcha and it's now passing the type-checks without and workaround. Thank you!

**Comment by zoryana94** [comment]
Thank you a lot for pointing that out and for your contribution, @JAD3N! 👍
