### ISSUE TITLE
`.execute` sometimes returns `undefined` instead of a `Promise`

### ISSUE THREAD

**Issue by steved-stripe** [hCaptcha/react-hcaptcha#237]
if `this.isReady()` is `false`, then this code path will return `undefined`:

https://github.com/hCaptcha/react-hcaptcha/blob/491bb96fe8c302b4c9f95c53547b92411c3532a5/src/index.js#L335-L337

which isn't compatible with the typescript type:

https://github.com/hCaptcha/react-hcaptcha/blob/491bb96fe8c302b4c9f95c53547b92411c3532a5/types/index.d.ts#L53

**Comment by brdlyptrs** [comment]
Hi @steved-stripe, thanks for flagging. 

We'll take a further look into how we can align the internal functionality with what is expected. From what you mention, if async is set we want to make sure the code waits until ready to execute instead of immediately bailing if ready is false.

**Comment by gabrielferreira-imi** [comment]
Hi @steved-stripe, 

We just released a fix in our latest [1.11.0 version](https://github.com/hCaptcha/react-hcaptcha/releases/tag/1.11.0).
Could you please confirm it's working on your end?

Best regards,
hCaptcha dev team
