### ISSUE TITLE
Cannot adjust width of iframe [button]

### ISSUE THREAD

**Issue by christianbalderrama** [hCaptcha/react-hcaptcha#24]
As declared in the docs the `sizes` available are `["normal", "compact", "invisible"]` but nothing is mentioned about styling the component e.g adjusting the size of the captcha.

The scenario that I am into is that I want to fill 100% width of a specific container but limited to adjusting the sizes.

I have tried overriding the `anchor-content` class `width` but it is being cut because the `iframe` width should be changed as well.

**Comment by e271828-** [comment]
@christianbalderrama the iframe is a modal, and will vary greatly in dimensions depending on the particular challenge being served. Resizing it through an override is likely to break.

**Comment by christianbalderrama** [comment]
The modal pop up with the challenge was not the problem but the iframe itself when it is first being rendered

**Comment by brdlyptrs** [comment]
Hi @christianbalderrama the iframe is set to a specific size on purpose. Adjusting the size manually could cause text to be cut off or prevent the user from interacting with the elements on the checkbox as intended.
