### ISSUE TITLE
ReferenceError: performance is not defined

### ISSUE THREAD

**Issue by KrallXZ** [hCaptcha/react-hcaptcha#25]
It happens on SSR.
Node.js version: v12.16.1

**Comment by e271828-** [comment]
@KrallXZ try adding:
`const { performance } = require('perf_hooks');`

for SSR. PRs welcome to add this to the README :)

**Comment by helloitsm3** [comment]
I'm using NextJS. Where do I insert this code?

**Comment by brdlyptrs** [comment]
Closing this as it should be fixed in the following PR https://github.com/hCaptcha/react-hcaptcha/pull/26. Make sure to use the latest version: `0.1.8`.
