### ISSUE TITLE
It's throwing prop id did not match error

### ISSUE THREAD

**Issue by helloitsm3** [hCaptcha/react-hcaptcha#28]
![image](https://user-images.githubusercontent.com/13825491/80054292-67e30d80-8551-11ea-914f-776df7717619.png)

**Comment by brdlyptrs** [comment]
Hi @helloitsm3, this looks like an error caused when using Server Side Rendering. Since you can have multiple captchas per application, the component dynamically generates a unique id for each one. The hCaptcha API uses the id to render the captcha to the correct element. One solution might be the ability to pass in your own **unique** id as a prop in order to prevent the `did not match` error shown.

**Comment by helloitsm3** [comment]
> 
> 
> Hi @helloitsm3, this looks like an error caused when using Server Side Rendering. Since you can have multiple captchas per application, the component dynamically generates a unique id for each one. The hCaptcha API uses the id to render the captcha to the correct element. One solution might be the ability to pass in your own **unique** id as a prop in order to prevent the `did not match` error shown.

I'm currently using NextJS which uses SSR by default. How do I ensure the server and client ID are in sync? There is also no ID prop for me to use my own unique ID

**Comment by msutkowski** [comment]
> > Hi @helloitsm3, this looks like an error caused when using Server Side Rendering. Since you can have multiple captchas per application, the component dynamically generates a unique id for each one. The hCaptcha API uses the id to render the captcha to the correct element. One solution might be the ability to pass in your own **unique** id as a prop in order to prevent the `did not match` error shown.
> 
> I'm currently using NextJS which uses SSR by default. How do I ensure the server and client ID are in sync? There is also no ID prop for me to use my own unique ID

I tested this on a Next page using the default recommendation of SSG without issue. Can you drop a shortened version of your page and it's data fetching method? Also, which version of Next? I'd be happy to help see if there is a quick solution.

**Comment by helloitsm3** [comment]
> 
> 
> > > Hi @helloitsm3, this looks like an error caused when using Server Side Rendering. Since you can have multiple captchas per application, the component dynamically generates a unique id for each one. The hCaptcha API uses the id to render the captcha to the correct element. One solution might be the ability to pass in your own **unique** id as a prop in order to prevent the `did not match` error shown.
> > 
> > 
> > I'm currently using NextJS which uses SSR by default. How do I ensure the server and client ID are in sync? There is also no ID prop for me to use my own unique ID
> 
> I tested this on a Next page using the default recommendation of SSG without issue. Can you drop a shortened version of your page and it's data fetching method? Also, which version of Next? I'd be happy to help see if there is a quick solution.

I'm using the latest NextJS version which is version 9.3.5.

`
import * as React from "react";
import axios from "axios";
import HCaptcha from "@hcaptcha/react-hcaptcha";

export class Form extends React.Component<{}, IState> {
  constructor(props: {}) {
    super(props);

    this.state = {
      name: "",
    };
  }

  handleChange(event: any) {
    this.setState({ name: event.target.value });
  }

  handleSubmit(event: any) {
    event.preventDefault();
    axios
      .post("/api/post-user", {
        name: this.state.name,
      })
      .then(() => {
        this.setState({
          name: "",
        });
      })
      .catch((error) => {
        console.log(error);
      });
  }

  handleVerificationSuccess = (token: string) => {
    console.log(`Token is: ${token}`);
  };

  render() {
    return (
      <div>
        <form onSubmit={(e) => this.handleSubmit(e)}>
          <HCaptcha
            sitekey="cce946a7-e25e-4998-870c-c1d38f6e1777"
            onVerify={(token) => this.handleVerificationSuccess(token)}
          />
          <input type="submit" value="Submit" />
        </form>
      </div>
    );
  }
}

interface IState {
  name: string;
}

export default Form;

`

**Comment by helloitsm3** [comment]
> 
> 
> > > Hi @helloitsm3, this looks like an error caused when using Server Side Rendering. Since you can have multiple captchas per application, the component dynamically generates a unique id for each one. The hCaptcha API uses the id to render the captcha to the correct element. One solution might be the ability to pass in your own **unique** id as a prop in order to prevent the `did not match` error shown.
> > 
> > 
> > I'm currently using NextJS which uses SSR by default. How do I ensure the server and client ID are in sync? There is also no ID prop for me to use my own unique ID
> 
> I tested this on a Next page using the default recommendation of SSG without issue. Can you drop a shortened version of your page and it's data fetching method? Also, which version of Next? I'd be happy to help see if there is a quick solution.

Hi, are you able to solve this? I added hcaptcha component in a NextJS page too but it doesn't seem to be able to show since NextJS SSR is enabled by default

**Comment by helloitsm3** [comment]
Issue is solved. Used ComponentDidMount to ensure it's mounted before rendering HCaptcha
