### ISSUE TITLE
React native

### ISSUE THREAD

**Issue by wellingtonsilverio** [hCaptcha/react-hcaptcha#30]
I would like to put Hcaptcha in React native, can you create the project?

**Comment by posix4e** [comment]
Why don't you start it on your github and if we like it we will.

**Comment by gustavoferreirads** [comment]
@wellingtonsilverio Did you manage to integrate it with React Native

**Comment by e271828-** [comment]
This exists at https://github.com/hCaptcha/react-native-hcaptcha
