### ISSUE TITLE
Random widget id breaks SSR React apps (Including NextJS)

### ISSUE THREAD

**Issue by DarylPinto** [hCaptcha/react-hcaptcha#31]
When using a CSR/SSR hybrid react app (like with the extremely popular [NextJS](https://nextjs.org/)), the randomness of the `id` breaks the page due to mismatched renders:

```Warning: Prop `id` did not match. Server: "hcaptcha-abc" Client: "hcaptcha-xyz"```

My suggested fix is to allow the user to _optionally_ pass `id` as a prop that would take precedence over the `nanoId()` function currently used to generate the widget id.

**Comment by peterhanneman** [comment]
Why not prevent the component from rendering server side in the first place?

`(typeof window == 'object') && <HCaptcha />`

**Comment by peterhanneman** [comment]
Why not prevent the component from rendering server side in the first place?

`(typeof window === 'object') && <HCaptcha />`

**Comment by peterhanneman** [comment]
Was having the same issue with Next.js SSR and solved it by created a wrapper component then calling that from the parent with the required props.

```
import React from 'react';
import HCaptcha from '@hcaptcha/react-hcaptcha';

export default class HCaptchaWrapper extends React.Component {
  constructor(props) {
    super(props);
    this.state = { isMounted: false, ...props };
  }

  componentDidMount() { this.setState({ isMounted: true }); }

  render() {
    if (!this.state.isMounted) return '';
    return React.createElement(HCaptcha, this.state);
  }
}
```

**Comment by peterhanneman** [comment]
Was having the same issue with Next.js SSR and solved it by creating a wrapper component then calling that from the parent with the required props.

```
import React from 'react';
import HCaptcha from '@hcaptcha/react-hcaptcha';

export default class HCaptchaWrapper extends React.Component {
  constructor(props) {
    super(props);
    this.state = { isMounted: false, ...props };
  }

  componentDidMount() { this.setState({ isMounted: true }); }

  render() {
    if (!this.state.isMounted) return '';
    return React.createElement(HCaptcha, this.state);
  }
}
```

```
<HCaptchaWrapper
  sitekey="..."
  theme="light"
  size="normal"
  onVerify={handleVerificationSuccess}
/>
```

**Comment by brdlyptrs** [comment]
Hi @DarylPinto, this issue was brought up ealier, see [here](https://github.com/hCaptcha/react-hcaptcha/issues/28). We can add a custom prop as well to manually set the `ID`.

**Comment by DarylPinto** [comment]
@brdlyptrs Yes, I think that's a good suggestion. Earlier this evening I made a PR that adds the ability to use a custom `id` prop. Please have a look here: https://github.com/hCaptcha/react-hcaptcha/pull/32

**Comment by brdlyptrs** [comment]
Sorry, I did not see that PR initially. I ended up making this [PR](https://github.com/hCaptcha/react-hcaptcha/pull/33) which was originally started before the previous issue https://github.com/hCaptcha/react-hcaptcha/issues/28 was closed.

**Comment by amhoba** [comment]
For those who using function component with hooks, you can use this wrapper instead:

```javascript
import React, { useState, useEffect, useRef } from 'react'
import HCaptcha from '@hcaptcha/react-hcaptcha';

const HCaptchaWrapper = ({ sitekey, theme, size, onVerify }) => {

  const [isMounted, setIsMounted] = useState(false)

  useEffect(() => {
    setIsMounted(true)
  }, [])

  if (isMounted) {
    return <HCaptcha sitekey={sitekey} theme={theme} size={size} onVerify={onVerify}></HCaptcha>
  }
  else {
    return null
  }
}

export default HCaptchaWrapper
```

Also if you want to reset the component on form failure, I thought that its best to feed the `hcaptchaToken` to the component itself so the component will reset automatically. You just have to `setHcaptchaToken("")` when the form fails.

```javascript
import React, { useState, useEffect, useRef } from 'react'
import HCaptcha from '@hcaptcha/react-hcaptcha';

const HCaptchaWrapper = ({ sitekey, theme, size, onVerify, hcaptchaToken }) => {

  const [isMounted, setIsMounted] = useState(false)

  const element = useRef<HCaptcha>(null)

  useEffect(() => {
    setIsMounted(true)
  }, [])

  useEffect(() => {
    if (isMounted && hcaptchaToken == "") {
      element.current.resetCaptcha()
    }
  }, [hcaptchaToken])

  if (isMounted) {
    return <HCaptcha sitekey={sitekey} theme={theme} size={size} onVerify={onVerify} ref={element}></HCaptcha>
  }
  else {
    return null
  }
}

export default HCaptchaWrapper
```

**Comment by e271828-** [comment]
> For those who using function component with hooks, you can use this wrapper instead:
> ...

@amhoba would you like to PR this for the docs so it doesn't get lost?
