### ISSUE TITLE
Multiple hCaptcha's not rendering

### ISSUE THREAD

**Issue by skh-** [hCaptcha/react-hcaptcha#35]
Hello, thanks for the package.  It seems when there is multiple captchas, only the last one will render.  I've tried variations of adding and `id`, `key`, etc. with no luck.

Am I missing something or is this a bug?

https://codesandbox.io/s/optimistic-pond-0ll6g?file=/src/App.js

**Comment by e271828-** [comment]
Are you passing in the widget ID?

**Comment by brdlyptrs** [comment]
This issue was should have been solved in the following PR https://github.com/hCaptcha/react-hcaptcha/pull/40
