### ISSUE TITLE
Doesn't work with preact or preact/compat

### ISSUE THREAD

**Issue by rossPatton** [hCaptcha/react-hcaptcha#38]
See title.

I'm trying to convert my react application to preact, which will significantly reduce my app's bundle size. In my case, it would reduce my initial vendor bundle size by 30%, a significant decrease on my largest necessary file.

Everything else works fine, except that hcaptcha doesn't render.

Unfortunately, there's no error output. I believe react/preact issues usually have to do with lifecycles and re-rendering, but I can't be sure.

Wish I could provide more info. I am using preact/compat, not base preact, so in theory, everything that works with react should just work out of the box, no changes needed. So far, this has the case, except with the hcaptcha component.

I'm sure it's probably something minor and easily fixable, happy to help with debugging if it's useful?

Below are screenshots of what I'm seeing react vs preact

localhost login page with no preact aliases. just normal react
<img width="1251" alt="Screen Shot 2020-06-19 at 11 15 08 PM" src="https://user-images.githubusercontent.com/2379901/85190085-c7744580-b282-11ea-8a12-7291a8c26a67.png">

localhost login page with react packages aliased to preact/compat. No other changes. Hcaptcha doesn't load
<img width="1255" alt="Screen Shot 2020-06-19 at 11 12 15 PM" src="https://user-images.githubusercontent.com/2379901/85190097-e07cf680-b282-11ea-8a32-9adc916a1fa8.png">

**Comment by jembach** [comment]
I had the same problem. For me #39 has fixed it

**Comment by rossPatton** [comment]
nice! that solution makes perfect sense to me

**Comment by brdlyptrs** [comment]
This should have been resolved with the following PR https://github.com/hCaptcha/react-hcaptcha/pull/39

**Comment by rossPatton** [comment]
great! i'll give it a shot now
