### ISSUE TITLE
Enforce reinit on submit to prevent double-submission of passcodes

### ISSUE THREAD

**Issue by e271828-** [hCaptcha/react-hcaptcha#4]
It’s possible to preserve form state after submission (e.g. for react modals) which may lead to the hCaptcha passcode being cached in the popup->fill form->submit->popup->fill form->submit cycle. 

Since passcodes are one-time-use, this will always fail the second time the form is submitted.

Right now we rely on the website to handle this scenario correctly, but safest action would be to explicitly reset state on submit.

**Comment by posix4e** [comment]
"Since passcodes are one-time-use" -> So by this what he's saying is that siteverify cannot be called twice with the same passcode. Once we provide go / we delete the old token

**Comment by gaieges** [comment]
Resolved in #5 .. left it up to the user to manage and added docs
