### ISSUE TITLE
When trying to install your npm package it says that it doesn't exist

### ISSUE THREAD

**Issue by AndysonDK** [hCaptcha/react-hcaptcha#47]
![image](https://user-images.githubusercontent.com/28491857/89524839-8a89f100-d7e5-11ea-8eb2-7ded158e2352.png)

**Comment by e271828-** [comment]
Just tried:

```
$ npm install @hcaptcha/react-hcaptcha --save

+ @hcaptcha/react-hcaptcha@0.2.1
added 1 package from 1 contributor and audited 99 packages in 1.213s
found 0 vulnerabilities
```

I suspect you might have an issue with your registry or shell configuration. Try putting `@hcaptcha/react-hcaptcha` in quotes, and if that doesn't work try reinstalling npm.

**Comment by AndysonDK** [comment]
Okay now it works 😂 Just restarted my terminal and some other things maybe that fixed the issue
