### ISSUE TITLE
captchaRef.current.execute() results in type error (Typescript)

### ISSUE THREAD

**Issue by Nick-Mazuk** [hCaptcha/react-hcaptcha#51]
So I'm following one of the examples in the Readme for programmatically invoking hcaptcha.

https://codesandbox.io/s/react-hcaptchaform-example-forked-ngxge?file=/src/Form.jsx

And while the program works, the line `captchaRef.current.execute()` results in the following type error:

```
Property 'execute' does not exist on type 'never'.ts(2339)
```

Any ideas? I've installed the appropriate type files from Definitely Typed.

- React 16.13.1
- Next JS 9.5.2
- Typescript 4.0.2 (strict mode)
- @hcaptcha/react-hcaptcha 0.2.1

Here's a brief overview of the code:

```tsx
function Form() {
    const captchaRef = useRef(null)
    const onSubmit = () => captchaRef.current.execute()
    return (
        <form method="post" onSubmit={onSubmit}>
            <HCaptcha sitekey={.....} ref={captchaRef} />
            <button type="submit">Submit</button>
        </form>
    )
}
```

There's lots of other code as well, but this is enough to produce the type error on my end.

**Comment by e271828-** [comment]
@Nick-Mazuk looks like you might need to open a PR over on:

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/hcaptcha__react-hcaptcha

**Comment by Nick-Mazuk** [comment]
This seems to be resolved now. Use `HCatpcha` as the type for the ref. Full code:

```tsx
import HCaptcha from '@hcaptcha/react-hcaptcha'

function Form() {
    const captchaRef = useRef<HCaptcha>(null)
    const onSubmit = () => captchaRef.current.execute()
    return (
        <form method="post" onSubmit={onSubmit}>
            <HCaptcha sitekey={.....} ref={captchaRef} />
            <button type="submit">Submit</button>
        </form>
    )
}
```
