### ISSUE TITLE
Invisible hCaptcha, React.js

### ISSUE THREAD

**Issue by soia** [hCaptcha/react-hcaptcha#52]
The documentation says that you can watch a demo of invisible captcha using react.
Where is the demo link?
I can't find it.

I added size = "invisible"
But captcha isn't called when the form is submitted

"Please refer to the demo for examples of basic usage and an invisible hCaptcha."

**Comment by e271828-** [comment]
I believe you'll need to call `execute()` as in
https://github.com/hCaptcha/react-hcaptcha/blob/master/examples/src/index.js
  
```
  handleSubmit(event) {
    event.preventDefault()
    this.child.execute()
  }
```

**Comment by DSergiu** [comment]
Closing this as issue seems to be solved.
