### ISSUE TITLE
Hcaptcha Widget Does not Render After Refresh

### ISSUE THREAD

**Issue by dmeagher-indeed** [hCaptcha/react-hcaptcha#53]
When I refresh the react page that i'm using this hcaptcha widget on, the hcaptcha fails to rerender until I do a hard refresh (Shift-F5). I'm using typescript if that has anything to do with it.

**Comment by brdlyptrs** [comment]
Hi @dmeagher-indeed, does your console display any information or errors? Also, could you provide a snippet of the code?

**Comment by dmeagher-indeed** [comment]
`render() {
        const i18n = GettextFactory();
        const submit = i18n.gettext("Submit");
        return (
            <div className="Hcaptcha">
                <HCaptcha
                    sitekey={this.props.siteKey}
                    onVerify={this.onVerify}
                />
                <Button
                    onClick={this.onSubmit}>
                    {submit}
                </Button>
            </div>
        );
    }`
Here's the code snippet where I use the hcaptcha widget. I don't see any console errors pertaining to hcaptcha.

**Comment by e271828-** [comment]
> ```
> render() {
>         const i18n = GettextFactory();
>         const submit = i18n.gettext("Submit");
>         return (
>             <div className="Hcaptcha">
>                 <HCaptcha
>                     sitekey={this.props.siteKey}
>                     onVerify={this.onVerify}
>                 />
>                 <Button
>                     onClick={this.onSubmit}>
>                     {submit}
>                 </Button>
>             </div>
>         );
>     }
> ```
> 
> Here's the code snippet where I use the hcaptcha widget. I don't see any console errors pertaining to hcaptcha.

Does this happen only during development, or also if you push to a test environment and try there?

**Comment by brdlyptrs** [comment]
One thought, if its only in development, there may be an issue with compiling typescript and hot module updating. You could try commenting out this [line](https://github.com/hCaptcha/react-hcaptcha/blob/master/src/index.js#L109) in either the `src/index.js` or `dist/index.js`, depending on which one you are currently using for your application.

**Comment by dmeagher-indeed** [comment]
This happens in both local development and when we push to a test environment.

**Comment by e271828-** [comment]
> This happens in both local development and when we push to a test environment.

Sounds like something in your app is holding onto state. You could try, as a quick test, adding `renderCaptcha()` to your form/page init on the ref to see if that changes things.

Basic sketch of using refs: https://codesandbox.io/s/react-hcaptchaform-example-invisible-f7ekt

**Comment by brdlyptrs** [comment]
Using a button in a form element can cause the form to re-render if you do not use `event.preventDefault` in the `onSubmit` callback. See issue https://github.com/react-bootstrap/react-bootstrap/issues/1510 

I created another example [here](https://codesandbox.io/s/react-hcaptchasimple-form-9sv3t), that uses the native form `onSubmit` callback with `event.preventDefault`.

If you have any other information or code to share, please let us know. Otherwise, without any console errors or reproducabile steps, it is hard to say what may be the problem.

**Comment by dmeagher-indeed** [comment]
Using the ref to explicitly render the widget seems to have worked. Thanks for your help.
