### ISSUE TITLE
render null next.js

### ISSUE THREAD

**Issue by DevSamuelV** [hCaptcha/react-hcaptcha#54]
Im Using Next.js version 9.5.5

when using hCaptcha in the console it prints [hCaptcha] render: invalid container 'null' im not sure what the cause might be?

**Comment by DevSamuelV** [comment]
fixed the issue It was the env system not delivering the env

**Comment by supermooshman** [comment]
Hi @DevSamuelV any chance you have some more details on how you fixed it?

thx in advance!

**Comment by DevSamuelV** [comment]
@supermooshman I had to have hcaptcha wait for the environment variables to load
