### ISSUE TITLE
"Rate limited or network error. Please try again." after upgrading from 0.2.2 to 0.3.0

### ISSUE THREAD

**Issue by mfcochauxlaberge** [hCaptcha/react-hcaptcha#68]
I upgraded the library from 0.2.2 and 0.3.0 and I now get the following error message:

![image](https://user-images.githubusercontent.com/534861/106361544-8817d800-62ec-11eb-91a4-d938e711ad12.png)

I tried to look at this GitHub for documentation on a potential breaking change, but I couldn't find anything. The only tags are 0.3.0-alpha and 0.3.0. Where are the other tags?

I also get the following error log in the dev console:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://hcaptcha.com/checksiteconfig?host=localhost&sitekey=00000000-0000-0000-0000-000000000000&sc=1&swa=1. (Reason: CORS header “Access-Control-Allow-Origin” missing).

How can I fix this issue? Let me know if you need more information.

**Comment by e271828-** [comment]
@mfcochauxlaberge The issue is you are attempting to use `localhost`; see https://docs.hcaptcha.com/#local-development

**Comment by mfcochauxlaberge** [comment]
@e271828- Oh wow, I did have a host entry in `/etc/hosts` to solve that issue that I've used for maybe a year now, but for some reason, this morning, I typed `localhost` instead and didn't realize it... -_-

Thanks, all good now!
