### ISSUE TITLE
Allow user to override JSAPI URI

### ISSUE THREAD

**Issue by e271828-** [hCaptcha/react-hcaptcha#71]
i.e.

https://github.com/hCaptcha/react-hcaptcha/blob/796babebaf7cc592467456483767a1dea8f456f9/src/index.js#L19

should be:

`script.src = "${JSAPI_URI}?render=explicit&onload=hcaptchaOnLoad";`

**Comment by brdlyptrs** [comment]
We can add a property `apihost` in order to handle this use case.

**Comment by tttp** [comment]
I was going to add that issue but you were faster ;)

**Comment by e271828-** [comment]
> We can add a property `apihost` in order to handle this use case.

Sure, though remember we'll also need to deal with the other first-party params here, unless the user can set a bare string.
