### ISSUE TITLE
Language doesn't change

### ISSUE THREAD

**Issue by filipealonso** [hCaptcha/react-hcaptcha#82]
If someone enters a website and a default language is used to load and render the widget, if the visitor then selects another language the widget is re-rendered with a new `languageOverride` attribute but since the script was already requested in the default language before it won't load the new one and will still be displayed in a language the user doesn't understand.

The widget should be sensitive to language changes or maybe request individual dictionaries from the server in order to re-render in the correct language.

**Comment by e271828-** [comment]
I think this would need a new JSAPI hook to programmatically change the language of an existing widget. The user is able to do that via the UI already, but it's not exposed. 

The simplest thing without that would be to recreate the React component in this case, causing a reload of api.js with your new hl parameter.

**Comment by filipealonso** [comment]
> I think this would need a new JSAPI hook to programmatically change the language of an existing widget.

Yes, otherwise `languageOverride` doesn't make much sense as a parameter, other than to initialize the widget. In this regard, a new logic needs to be implemented.

**Comment by KevinDanikowski** [comment]
Out of curiosity, what is the use case that the user would change the browser language? @filipealonso , I have a multiple lingual site, but I don't imagine the users would change the language after the page has loaded

**Comment by filipealonso** [comment]
Simple @KevinDanikowski : anytime a user lands directly on that page as a first entry point and changes language for the first time there and then. That's when users usually change language... on their first entry page.

**Comment by e271828-** [comment]
Closing as there is now a user-visible UI element to select their preferred language, which re-renders everything. `hl` is intended to override at initialization time only.
