### ISSUE TITLE
Publish 1.0.0

### ISSUE THREAD

**Issue by dburles** [hCaptcha/react-hcaptcha#99]
The package has been published for ~3 years on major version 0, which means minor and patch releases are also treated as breaking changes and won't be automatically updated via `npm update` or `install`.

**Comment by e271828-** [comment]
Targeting next week for this.

**Comment by Rexogamer** [comment]
Any news on this? Probably releasable at this point :)

**Comment by e271828-** [comment]
@Rexogamer  Yep, just released :)
